name: todos
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation: ^2.4.4
  hooks_riverpod:
  riverpod:
  uuid: ^4.0.4

dev_dependencies:
  build_runner: ^2.0.0
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  riverpod_lint:
  flutter_lints:
  freezed: ^2.5.8
dependency_overrides:
  flutter_riverpod:
  hooks_riverpod:
  riverpod:

flutter:
  uses-material-design: true
